module.exports = {
  singleQuote: true,
  jsxBracketSameLine: false,
  eslintIntegration: false,
  tslintIntegration: true,
  requireConfig: false,
  stylelintIntegration: false,
  arrowParens: 'always',
  bracketSpacing: true,
  embeddedLanguageFormatting: 'auto',
  htmlWhitespaceSensitivity: 'css',
  insertPragma: false,
  jsxSingleQuote: true,
  tsxSingleQuote: true,
  printWidth: 80,
  proseWrap: 'preserve',
  quoteProps: 'as-needed',
  requirePragma: false,
  semi: false,
  useTabs: false,
  tabWidth: 2,
  trailingComma: 'es5',
}
